webtalk_init -webtalk_dir /home/jupiter/work/redefine_test/chisel_test/testSlave/testSlave.sim/sim_1/behav/xsim/xsim.dir/tb_slave_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jan 31 16:34:53 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211363136_0_0_161" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d824616c-5c74-4858-bc16-a1d5d8bd9898" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f1e5e75c14504b459089d312f14243b8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "106" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2553.068 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "133420_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4248764170 -regid "211363136_0_0_161" -xml /home/jupiter/work/redefine_test/chisel_test/testSlave/testSlave.sim/sim_1/behav/xsim/xsim.dir/tb_slave_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/jupiter/work/redefine_test/chisel_test/testSlave/testSlave.sim/sim_1/behav/xsim/xsim.dir/tb_slave_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/jupiter/work/redefine_test/chisel_test/testSlave/testSlave.sim/sim_1/behav/xsim/xsim.dir/tb_slave_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
