######################################################################
#
# File name : tb_test_64_wave.do
# Created on: Mon Jan 28 15:51:58 IST 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
