######################################################################
#
# File name : tb_test_64_simulate.do
# Created on: Mon Jan 28 15:52:09 IST 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_test_64 xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_test_64_wave.do}

view wave
view structure
view signals

log -r /*

do {tb_test_64.udo}

run 1000ns
